apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade
  labels:
    app: trade
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trade
  template:
    metadata:
      labels:
        app: trade
    spec:
      containers:
        - name: trade
          image: 052937454741.dkr.ecr.ap-northeast-2.amazonaws.com/admin08-mybtrade/trade:v6
          ports:
            - containerPort: 8080
            resources:
              limits:
                cpu: "2"
              requests:
                cpu: "1"